services:
  postgres:
    image: postgres:17
    ports:
      - "5433:5432"
    volumes:
      - "./volumes/postgres/data:/var/lib/postgresql/data/"
    environment:
      - POSTGRES_PASSWORD=augusto18
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dbFiumba